<p><strong>Подвиг 2.</strong> Вы видите в консольном окне следующие строчки сообщения об ошибке:</p>

<p>Traceback (most recent call last):<br>
  File "D:\Python\Projects\oop\ex1.py", line 26, in &lt;module&gt;<br>
    el = Ellipse(1, 2, 3, 4, '1')<br>
  File "D:\Python\Projects\oop\ex1.py", line 12, in __init__<br>
    super().__init__(width, color)<br>
  File "D:\Python\Projects\oop\ex1.py", line 4, in __init__<br>
    raise ValueError('неверные параметры фигуры')<br>
ValueError: неверные параметры фигуры</p>

<p>Выберите все верные утверждения, которые можно сделать из этого вывода.</p>